exclude:
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- dap.md
- uxtesting.md
- work
- ".sass-cache"

# Site metadata
title: "analytics.usa.gov | The US government's web traffic."
description: "Official data on web traffic to hundreds of US federal government websites. Published by the Digital Analytics Program."

# site's own URL, and data root
# url: https://analytics.usa.gov
# data_url: https://analytics.usa.gov/data/live

# For development, when using `jekyll serve`
url: http://localhost:4000
# For development, when using:
#   analytics --output=[dir]
# and running from [dir]:
#   serve
data_url: http://localhost:3000

# GitHub information
org_name: GSA
repo_name: analytics.usa.gov

# twitter information
twitter: usgsa
