exclude:
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- dap.md
- uxtesting.md
- work
- ".sass-cache"

# defaults
defaults:
  -
    scope:
      path: ""
      type: agencies
    values:
      layout: default

collections:
  agencies:
    output: true
    permalink: /:path/

# Site metadata
title: "analytics.usa.gov | The US government's web traffic."
dropdown_title: All Agencies
description: "Official data on web traffic to hundreds of US federal government websites. Published by the Digital Analytics Program."

# site's own URL, and data root
data_url: https://analytics.usa.gov/data/live

# GitHub information
org_name: GSA
repo_name: analytics.usa.gov

# twitter information
twitter: usgsa

sass:
  sass_dir: sass
  style: nested

url: https://pages.geramirez.gov/analytics.usa.gov
baseurl: /analytics.usa.gov
